version: 2.1
jobs:
  deploy_Server:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - terraform init
      - terraform apply -input=false
workflows:
  build_deploy:
    jobs:
      - deploy_server
