version: 2.1
jobs:
  deploy_server:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform init
      - run: terraform apply -var="AdminPassword=${AdminPassword}" -input=false
workflows:
  build_deploy:
    jobs:
      - deploy_server
